# Generated by Django 2.2.6 on 2019-10-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Real', models.CharField(max_length=200)),
                ('Nombre_Artistico', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
                ('Pais_Origen', models.CharField(max_length=200)),
                ('Nacionalidad', models.CharField(max_length=200)),
                ('Inicio_Actividad', models.IntegerField()),
            ],
        ),
    ]
